import { disconnect } from "process";

// import { Background } from './Background';
export const LoaderConfig = {
    // frame : "/src/sprites/SlotMachine_3x5.png",
    Background:  "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed :  "/src/sprites/ButtonAutoSpinHover_1.png",
    BetPanel :  "/src/sprites/PanelTotalBet.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    winPanel :  "/src/sprites/PanelWin.png",    
    balancePanel :  "/src/sprites/PanelBalance.png",
    // fireVase :  "/src/sprites/Vase.png",
    // PanelJackpot:  "/src/sprites/PanelJackpot.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    rulesBtn :  "/src/sprites/ButtonRules.png",
    rulesBtnH :  "/src/sprites/ButtonRulesHover.png",
    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButtonHover.png",
    leftPlank: "src/sprites/leftPlank.png",
    rightPlank: "src/sprites/rightPlank.png",
    topPlank: "src/sprites/topPlank.png",
    bottomPlank: "src/sprites/bottomPlank.png",
    upPlnak: "src/sprites/Up.png",
    leftLanterns: "src/sprites/leftLanterns.png",
    rightLanterns: "src/sprites/rightLanterns.png",
    popupBgimg: "src/sprites/AboutPanel.png",
    messagePopup: "src/sprites/messagepopup.png",
    normalButton: "src/sprites/NormalButton.png",
    yesButton: "src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButtonHover: "src/sprites/noButtonHover.png",
    noButton: "src/sprites/noButton.png",
    bigWinPopup: "src/sprites/BigWinPopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinpopup.png",
    jackpotPopup: "src/sprites/jackpotPopup.png",
    freeSpinPopup: "src/sprites/FreeSpinPopup.png",
    freeSpinStartButton: "src/sprites/freeSpinStartButton.png",
    freeSpinStartButtonPressed: "src/sprites/freeSpinStartButton.png",
    spinCircle: "src/sprites/SpinCircle.png",
    spinCenter: "src/sprites/SpinCenter.png",
    wheelBg: "src/sprites/WheelBg.png",

    logo: "src/sprites/vikingsLogo.png",
    assetsloader: "src/sprites/assetsLoader.png",
    loaderBg: "src/sprites/loaderBg.png",
    stairs: "src/sprites/Stair.png",
    reelBg: "src/sprites/reelBg.png",   
    column: "src/sprites/columnLeft.png",
    snow: "src/sprites/Snow.png",
    roof:"src/sprites/Roof.png",
    winLine: "src/sprites/WinLine.png",
    lineSymbols: "src/sprites/LineSymbols.png",
    settingPopup:"src/sprites/settingPopup.png",
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    toggleBar: "src/sprites/ToggleBar.png",
    onButton: "src/sprites/On.png",
    offButton: "src/sprites/Off.png",
    headingImage: "src/sprites/PayTable_.png",
    payLines: "src/sprites/payLines.png",
    popupbg: "src/sprites/PopupBg.jpg",
    scrollBg: "src/sprites/ScrollBar.png",
    scroller:"src/sprites/Roller.png",
    minorSymbolsHeading: "src/sprites/MoniorSymbols.png",
    majorSymbolHeading: "src/sprites/MajorSymbolsHeading.png",
    specialSymBolHeading: "src/sprites/SpecialSymbolHeading.png",
    GoldenChinaTown: "src/sprites/GoldenChinaTownLogo.png",
    lineButton: "src/sprites/lineButton.png",
    settingText: "src/sprites/SettingButton.png",
    InfoPopupBg: "src/sprites/infoBg.jpg",
    disconnectClose: "src/sprites/disconnectClose.png",
    
    slots0_0 :  "/src/sprites/Symbols/Ten/Ten1.png",
    slots0_1 :  "/src/sprites/Symbols/Ten/Ten2.png",
    slots0_2 :  "/src/sprites/Symbols/Ten/Ten3.png",
    slots0_3 :  "/src/sprites/Symbols/Ten/Ten4.png",
    slots0_4 :  "/src/sprites/Symbols/Ten/Ten5.png",
    slots0_5 :  "/src/sprites/Symbols/Ten/Ten6.png",
    slots0_6 :  "/src/sprites/Symbols/Ten/Ten7.png",
    slots0_7 :  "/src/sprites/Symbols/Ten/Ten8.png",
    slots0_8 :  "/src/sprites/Symbols/Ten/Ten9.png",
    slots0_9 :  "/src/sprites/Symbols/Ten/Ten10.png",
    slots0_10:  "/src/sprites/Symbols/Ten/Ten11.png",
    slots0_11:  "/src/sprites/Symbols/Ten/Ten12.png",
    slots0_12:  "/src/sprites/Symbols/Ten/Ten13.png",
    slots0_13:  "/src/sprites/Symbols/Ten/Ten14.png",
    slots0_14:  "/src/sprites/Symbols/Ten/Ten15.png",
    slots0_15:  "/src/sprites/Symbols/Ten/Ten16.png",
    slots0_16:  "/src/sprites/Symbols/Ten/Ten17.png",
    slots0_17:  "/src/sprites/Symbols/Ten/Ten18.png",
    slots0_18:  "/src/sprites/Symbols/Ten/Ten19.png",
    slots0_19:  "/src/sprites/Symbols/Ten/Ten20.png",
    slots0_20:  "/src/sprites/Symbols/Ten/Ten21.png",
    slots0_21:  "/src/sprites/Symbols/Ten/Ten22.png",
    slots0_22:  "/src/sprites/Symbols/Ten/Ten23.png",
    slots0_23:  "/src/sprites/Symbols/Ten/Ten24.png",

    slots1_0 :  "/src/sprites/Symbols/J/J1.png",
    slots1_1 :  "/src/sprites/Symbols/J/J2.png",
    slots1_2 :  "/src/sprites/Symbols/J/J3.png",
    slots1_3 :  "/src/sprites/Symbols/J/J4.png",
    slots1_4 :  "/src/sprites/Symbols/J/J5.png",
    slots1_5 :  "/src/sprites/Symbols/J/J6.png",
    slots1_6 :  "/src/sprites/Symbols/J/J7.png",
    slots1_7 :  "/src/sprites/Symbols/J/J8.png",
    slots1_8 :  "/src/sprites/Symbols/J/J9.png",
    slots1_9 :  "/src/sprites/Symbols/J/J10.png",
    slots1_10:  "/src/sprites/Symbols/J/J11.png",
    slots1_11:  "/src/sprites/Symbols/J/J12.png",
    slots1_12:  "/src/sprites/Symbols/J/J13.png",
    slots1_13:  "/src/sprites/Symbols/J/J14.png",
    slots1_14:  "/src/sprites/Symbols/J/J15.png",
    slots1_15:  "/src/sprites/Symbols/J/J16.png",
    slots1_16:  "/src/sprites/Symbols/J/J17.png",
    slots1_17:  "/src/sprites/Symbols/J/J18.png",
    slots1_18:  "/src/sprites/Symbols/J/J19.png",
    slots1_19:  "/src/sprites/Symbols/J/J20.png",
    slots1_20:  "/src/sprites/Symbols/J/J21.png",
    slots1_21:  "/src/sprites/Symbols/J/J22.png",
    slots1_22:  "/src/sprites/Symbols/J/J23.png",
    slots1_23:  "/src/sprites/Symbols/J/J24.png",

    slots2_0 :  "/src/sprites/Symbols/Q/Q1.png",
    slots2_1 :  "/src/sprites/Symbols/Q/Q2.png",
    slots2_2 :  "/src/sprites/Symbols/Q/Q3.png",
    slots2_3 :  "/src/sprites/Symbols/Q/Q4.png",
    slots2_4 :  "/src/sprites/Symbols/Q/Q5.png",
    slots2_5 :  "/src/sprites/Symbols/Q/Q6.png",
    slots2_6 :  "/src/sprites/Symbols/Q/Q7.png",
    slots2_7 :  "/src/sprites/Symbols/Q/Q8.png",
    slots2_8 :  "/src/sprites/Symbols/Q/Q9.png",
    slots2_9 :  "/src/sprites/Symbols/Q/Q10.png",
    slots2_10:  "/src/sprites/Symbols/Q/Q11.png",
    slots2_11:  "/src/sprites/Symbols/Q/Q12.png",
    slots2_12:  "/src/sprites/Symbols/Q/Q13.png",
    slots2_13:  "/src/sprites/Symbols/Q/Q14.png",
    slots2_14:  "/src/sprites/Symbols/Q/Q15.png",
    slots2_15:  "/src/sprites/Symbols/Q/Q16.png",
    slots2_16:  "/src/sprites/Symbols/Q/Q17.png",
    slots2_17:  "/src/sprites/Symbols/Q/Q18.png",
    slots2_18:  "/src/sprites/Symbols/Q/Q19.png",
    slots2_19:  "/src/sprites/Symbols/Q/Q20.png",
    slots2_20:  "/src/sprites/Symbols/Q/Q21.png",
    slots2_21:  "/src/sprites/Symbols/Q/Q22.png",
    slots2_22:  "/src/sprites/Symbols/Q/Q23.png",
    slots2_23:  "/src/sprites/Symbols/Q/Q24.png",
    
    slots3_0 :  "/src/sprites/Symbols/K/K1.png",
    slots3_1 :  "/src/sprites/Symbols/K/K2.png",
    slots3_2 :  "/src/sprites/Symbols/K/K3.png",
    slots3_3 :  "/src/sprites/Symbols/K/K4.png",
    slots3_4 :  "/src/sprites/Symbols/K/K5.png",
    slots3_5 :  "/src/sprites/Symbols/K/K6.png",
    slots3_6 :  "/src/sprites/Symbols/K/K7.png",
    slots3_7 :  "/src/sprites/Symbols/K/K8.png",
    slots3_8 :  "/src/sprites/Symbols/K/K9.png",
    slots3_9 :  "/src/sprites/Symbols/K/K10.png",
    slots3_10:  "/src/sprites/Symbols/K/K11.png",
    slots3_11:  "/src/sprites/Symbols/K/K12.png",
    slots3_12:  "/src/sprites/Symbols/K/K13.png",
    slots3_13:  "/src/sprites/Symbols/K/K14.png",
    slots3_14:  "/src/sprites/Symbols/K/K15.png",
    slots3_15:  "/src/sprites/Symbols/K/K16.png",
    slots3_16:  "/src/sprites/Symbols/K/K17.png",
    slots3_17:  "/src/sprites/Symbols/K/K18.png",
    slots3_18:  "/src/sprites/Symbols/K/K19.png",
    slots3_19:  "/src/sprites/Symbols/K/K20.png",
    slots3_20:  "/src/sprites/Symbols/K/K21.png",
    slots3_21:  "/src/sprites/Symbols/K/K22.png",
    slots3_22:  "/src/sprites/Symbols/K/K23.png",
    slots3_23:  "/src/sprites/Symbols/K/K24.png",

    slots4_0 :  "/src/sprites/Symbols/A/A1.png",
    slots4_1 :  "/src/sprites/Symbols/A/A2.png",
    slots4_2 :  "/src/sprites/Symbols/A/A3.png",
    slots4_3 :  "/src/sprites/Symbols/A/A4.png",
    slots4_4 :  "/src/sprites/Symbols/A/A5.png",
    slots4_5 :  "/src/sprites/Symbols/A/A6.png",
    slots4_6 :  "/src/sprites/Symbols/A/A7.png",
    slots4_7 :  "/src/sprites/Symbols/A/A8.png",
    slots4_8 :  "/src/sprites/Symbols/A/A9.png",
    slots4_9 :  "/src/sprites/Symbols/A/A10.png",
    slots4_10:  "/src/sprites/Symbols/A/A11.png",
    slots4_11:  "/src/sprites/Symbols/A/A12.png",
    slots4_12:  "/src/sprites/Symbols/A/A13.png",
    slots4_13:  "/src/sprites/Symbols/A/A14.png",
    slots4_14:  "/src/sprites/Symbols/A/A15.png",
    slots4_15:  "/src/sprites/Symbols/A/A16.png",
    slots4_16:  "/src/sprites/Symbols/A/A17.png",
    slots4_17:  "/src/sprites/Symbols/A/A18.png",
    slots4_18:  "/src/sprites/Symbols/A/A19.png",
    slots4_19:  "/src/sprites/Symbols/A/A20.png",
    slots4_20:  "/src/sprites/Symbols/A/A21.png",
    slots4_21:  "/src/sprites/Symbols/A/A22.png",
    slots4_22:  "/src/sprites/Symbols/A/A23.png",
    slots4_23:  "/src/sprites/Symbols/A/A24.png",

    slots5_0 :  "/src/sprites/Symbols/Sycee/Sycee1.png",
    slots5_1 :  "/src/sprites/Symbols/Sycee/Sycee2.png",
    slots5_2 :  "/src/sprites/Symbols/Sycee/Sycee3.png",
    slots5_3 :  "/src/sprites/Symbols/Sycee/Sycee4.png",
    slots5_4 :  "/src/sprites/Symbols/Sycee/Sycee5.png",
    slots5_5 :  "/src/sprites/Symbols/Sycee/Sycee6.png",
    slots5_6 :  "/src/sprites/Symbols/Sycee/Sycee7.png",
    slots5_7 :  "/src/sprites/Symbols/Sycee/Sycee8.png",
    slots5_8 :  "/src/sprites/Symbols/Sycee/Sycee9.png",
    slots5_9 :  "/src/sprites/Symbols/Sycee/Sycee10.png",
    slots5_10:  "/src/sprites/Symbols/Sycee/Sycee11.png",
    slots5_11:  "/src/sprites/Symbols/Sycee/Sycee12.png",
    slots5_12:  "/src/sprites/Symbols/Sycee/Sycee13.png",
    slots5_13:  "/src/sprites/Symbols/Sycee/Sycee14.png",
    slots5_14:  "/src/sprites/Symbols/Sycee/Sycee15.png",
    slots5_15:  "/src/sprites/Symbols/Sycee/Sycee16.png",
    slots5_16:  "/src/sprites/Symbols/Sycee/Sycee17.png",
    slots5_17:  "/src/sprites/Symbols/Sycee/Sycee18.png",
    slots5_18:  "/src/sprites/Symbols/Sycee/Sycee19.png",
    slots5_19:  "/src/sprites/Symbols/Sycee/Sycee20.png",
    slots5_20:  "/src/sprites/Symbols/Sycee/Sycee21.png",
    slots5_21:  "/src/sprites/Symbols/Sycee/Sycee22.png",
    slots5_22:  "/src/sprites/Symbols/Sycee/Sycee23.png",
    slots5_23:  "/src/sprites/Symbols/Sycee/Sycee24.png",

    slots6_0 :  "/src/sprites/Symbols/Fan/Fan1.png",
    slots6_1 :  "/src/sprites/Symbols/Fan/Fan2.png",
    slots6_2 :  "/src/sprites/Symbols/Fan/Fan3.png",
    slots6_3 :  "/src/sprites/Symbols/Fan/Fan4.png",
    slots6_4 :  "/src/sprites/Symbols/Fan/Fan5.png",
    slots6_5 :  "/src/sprites/Symbols/Fan/Fan6.png",
    slots6_6 :  "/src/sprites/Symbols/Fan/Fan7.png",
    slots6_7 :  "/src/sprites/Symbols/Fan/Fan8.png",
    slots6_8 :  "/src/sprites/Symbols/Fan/Fan9.png",
    slots6_9 :  "/src/sprites/Symbols/Fan/Fan10.png",
    slots6_10:  "/src/sprites/Symbols/Fan/Fan11.png",
    slots6_11:  "/src/sprites/Symbols/Fan/Fan12.png",
    slots6_12:  "/src/sprites/Symbols/Fan/Fan13.png",
    slots6_13:  "/src/sprites/Symbols/Fan/Fan14.png",
    slots6_14:  "/src/sprites/Symbols/Fan/Fan15.png",
    slots6_15:  "/src/sprites/Symbols/Fan/Fan16.png",
    slots6_16:  "/src/sprites/Symbols/Fan/Fan17.png",
    slots6_17:  "/src/sprites/Symbols/Fan/Fan18.png",
    slots6_18:  "/src/sprites/Symbols/Fan/Fan19.png",
    slots6_19:  "/src/sprites/Symbols/Fan/Fan20.png",
    slots6_20:  "/src/sprites/Symbols/Fan/Fan21.png",
    slots6_21:  "/src/sprites/Symbols/Fan/Fan22.png",
    slots6_22:  "/src/sprites/Symbols/Fan/Fan23.png",
    slots6_23:  "/src/sprites/Symbols/Fan/Fan24.png",

    slots7_0 :  "/src/sprites/Symbols/Teapot/Teapot1.png",
    slots7_1 :  "/src/sprites/Symbols/Teapot/Teapot2.png",
    slots7_2 :  "/src/sprites/Symbols/Teapot/Teapot3.png",
    slots7_3 :  "/src/sprites/Symbols/Teapot/Teapot4.png",
    slots7_4 :  "/src/sprites/Symbols/Teapot/Teapot5.png",
    slots7_5 :  "/src/sprites/Symbols/Teapot/Teapot6.png",
    slots7_6 :  "/src/sprites/Symbols/Teapot/Teapot7.png",
    slots7_7 :  "/src/sprites/Symbols/Teapot/Teapot8.png",
    slots7_8 :  "/src/sprites/Symbols/Teapot/Teapot9.png",
    slots7_9 :  "/src/sprites/Symbols/Teapot/Teapot10.png",
    slots7_10:  "/src/sprites/Symbols/Teapot/Teapot11.png",
    slots7_11:  "/src/sprites/Symbols/Teapot/Teapot12.png",
    slots7_12:  "/src/sprites/Symbols/Teapot/Teapot13.png",
    slots7_13:  "/src/sprites/Symbols/Teapot/Teapot14.png",
    slots7_14:  "/src/sprites/Symbols/Teapot/Teapot15.png",
    slots7_15:  "/src/sprites/Symbols/Teapot/Teapot16.png",
    slots7_16:  "/src/sprites/Symbols/Teapot/Teapot17.png",
    slots7_17:  "/src/sprites/Symbols/Teapot/Teapot18.png",
    slots7_18:  "/src/sprites/Symbols/Teapot/Teapot19.png",
    slots7_19:  "/src/sprites/Symbols/Teapot/Teapot20.png",
    slots7_20:  "/src/sprites/Symbols/Teapot/Teapot21.png",
    slots7_21:  "/src/sprites/Symbols/Teapot/Teapot22.png",
    slots7_22:  "/src/sprites/Symbols/Teapot/Teapot23.png",
    slots7_23:  "/src/sprites/Symbols/Teapot/Teapot24.png",

    slots8_0 :  "/src/sprites/Symbols/Coin/Coins1.png",
    slots8_1 :  "/src/sprites/Symbols/Coin/Coins2.png",
    slots8_2 :  "/src/sprites/Symbols/Coin/Coins3.png",
    slots8_3 :  "/src/sprites/Symbols/Coin/Coins4.png",
    slots8_4 :  "/src/sprites/Symbols/Coin/Coins5.png",
    slots8_5 :  "/src/sprites/Symbols/Coin/Coins6.png",
    slots8_6 :  "/src/sprites/Symbols/Coin/Coins7.png",
    slots8_7 :  "/src/sprites/Symbols/Coin/Coins8.png",
    slots8_8 :  "/src/sprites/Symbols/Coin/Coins9.png",
    slots8_9 :  "/src/sprites/Symbols/Coin/Coins10.png",
    slots8_10:  "/src/sprites/Symbols/Coin/Coins11.png",
    slots8_11:  "/src/sprites/Symbols/Coin/Coins12.png",
    slots8_12:  "/src/sprites/Symbols/Coin/Coins13.png",
    slots8_13:  "/src/sprites/Symbols/Coin/Coins14.png",
    slots8_14:  "/src/sprites/Symbols/Coin/Coins15.png",
    slots8_15:  "/src/sprites/Symbols/Coin/Coins16.png",
    slots8_16:  "/src/sprites/Symbols/Coin/Coins17.png",
    slots8_17:  "/src/sprites/Symbols/Coin/Coins18.png",
    slots8_18:  "/src/sprites/Symbols/Coin/Coins19.png",
    slots8_19:  "/src/sprites/Symbols/Coin/Coins20.png",
    slots8_20:  "/src/sprites/Symbols/Coin/Coins21.png",
    slots8_21:  "/src/sprites/Symbols/Coin/Coins22.png",
    slots8_22:  "/src/sprites/Symbols/Coin/Coins23.png",
    slots8_23:  "/src/sprites/Symbols/Coin/Coins24.png",

    
    slots9_0 :  "/src/sprites/Symbols/Scroll/Scroll1.png",
    slots9_1 :  "/src/sprites/Symbols/Scroll/Scroll2.png",
    slots9_2 :  "/src/sprites/Symbols/Scroll/Scroll3.png",
    slots9_3 :  "/src/sprites/Symbols/Scroll/Scroll4.png",
    slots9_4 :  "/src/sprites/Symbols/Scroll/Scroll5.png",
    slots9_5 :  "/src/sprites/Symbols/Scroll/Scroll6.png",
    slots9_6 :  "/src/sprites/Symbols/Scroll/Scroll7.png",
    slots9_7 :  "/src/sprites/Symbols/Scroll/Scroll8.png",
    slots9_8 :  "/src/sprites/Symbols/Scroll/Scroll9.png",
    slots9_9 :  "/src/sprites/Symbols/Scroll/Scroll10.png",
    slots9_10:  "/src/sprites/Symbols/Scroll/Scroll11.png",
    slots9_11:  "/src/sprites/Symbols/Scroll/Scroll12.png",
    slots9_12:  "/src/sprites/Symbols/Scroll/Scroll13.png",
    slots9_13:  "/src/sprites/Symbols/Scroll/Scroll14.png",
    slots9_14:  "/src/sprites/Symbols/Scroll/Scroll15.png",
    slots9_15:  "/src/sprites/Symbols/Scroll/Scroll16.png",
    slots9_16:  "/src/sprites/Symbols/Scroll/Scroll17.png",
    slots9_17:  "/src/sprites/Symbols/Scroll/Scroll18.png",
    slots9_18:  "/src/sprites/Symbols/Scroll/Scroll19.png",
    slots9_19:  "/src/sprites/Symbols/Scroll/Scroll20.png",
    slots9_20:  "/src/sprites/Symbols/Scroll/Scroll21.png",
    slots9_21:  "/src/sprites/Symbols/Scroll/Scroll22.png",
    slots9_22:  "/src/sprites/Symbols/Scroll/Scroll23.png",
    slots9_23:  "/src/sprites/Symbols/Scroll/Scroll24.png",

    slots10_0 :  "/src/sprites/Symbols/Jackpot/Jackpot1.png",
    slots10_1 :  "/src/sprites/Symbols/Jackpot/Jackpot2.png",
    slots10_2 :  "/src/sprites/Symbols/Jackpot/Jackpot3.png",
    slots10_3 :  "/src/sprites/Symbols/Jackpot/Jackpot4.png",
    slots10_4 :  "/src/sprites/Symbols/Jackpot/Jackpot5.png",
    slots10_5 :  "/src/sprites/Symbols/Jackpot/Jackpot6.png",
    slots10_6 :  "/src/sprites/Symbols/Jackpot/Jackpot7.png",
    slots10_7 :  "/src/sprites/Symbols/Jackpot/Jackpot8.png",
    slots10_8 :  "/src/sprites/Symbols/Jackpot/Jackpot9.png",
    slots10_9 :  "/src/sprites/Symbols/Jackpot/Jackpot10.png",
    slots10_10:  "/src/sprites/Symbols/Jackpot/Jackpot11.png",
    slots10_11:  "/src/sprites/Symbols/Jackpot/Jackpot12.png",
    slots10_12:  "/src/sprites/Symbols/Jackpot/Jackpot13.png",
    slots10_13:  "/src/sprites/Symbols/Jackpot/Jackpot14.png",
    slots10_14:  "/src/sprites/Symbols/Jackpot/Jackpot15.png",
    slots10_15:  "/src/sprites/Symbols/Jackpot/Jackpot16.png",
    slots10_16:  "/src/sprites/Symbols/Jackpot/Jackpot17.png",
    slots10_17:  "/src/sprites/Symbols/Jackpot/Jackpot18.png",
    slots10_18:  "/src/sprites/Symbols/Jackpot/Jackpot19.png",
    slots10_19:  "/src/sprites/Symbols/Jackpot/Jackpot20.png",
    slots10_20:  "/src/sprites/Symbols/Jackpot/Jackpot21.png",
    slots10_21:  "/src/sprites/Symbols/Jackpot/Jackpot22.png",
    slots10_22:  "/src/sprites/Symbols/Jackpot/Jackpot23.png",
    slots10_23:  "/src/sprites/Symbols/Jackpot/Jackpot24.png",
    slots10_24:  "/src/sprites/Symbols/Jackpot/Jackpot25.png",
    slots10_25:  "/src/sprites/Symbols/Jackpot/Jackpot26.png",
    slots10_26:  "/src/sprites/Symbols/Jackpot/Jackpot27.png",
    slots10_27:  "/src/sprites/Symbols/Jackpot/Jackpot28.png",
    slots10_28:  "/src/sprites/Symbols/Jackpot/Jackpot29.png",
    slots10_29:  "/src/sprites/Symbols/Jackpot/Jackpot30.png",
    slots10_30:  "/src/sprites/Symbols/Jackpot/Jackpot31.png",
    slots10_31:  "/src/sprites/Symbols/Jackpot/Jackpot32.png",
    slots10_32:  "/src/sprites/Symbols/Jackpot/Jackpot33.png",
    slots10_33:  "/src/sprites/Symbols/Jackpot/Jackpot34.png",
    slots10_34:  "/src/sprites/Symbols/Jackpot/Jackpot35.png",
    slots10_35:  "/src/sprites/Symbols/Jackpot/Jackpot36.png",
    slots10_36:  "/src/sprites/Symbols/Jackpot/Jackpot37.png",
    slots10_37:  "/src/sprites/Symbols/Jackpot/Jackpot38.png",
    slots10_38:  "/src/sprites/Symbols/Jackpot/Jackpot39.png",
    slots10_39:  "/src/sprites/Symbols/Jackpot/Jackpot40.png",
    slots10_40:  "/src/sprites/Symbols/Jackpot/Jackpot41.png",
    slots10_41:  "/src/sprites/Symbols/Jackpot/Jackpot42.png",
    slots10_42:  "/src/sprites/Symbols/Jackpot/Jackpot43.png",
    slots10_43:  "/src/sprites/Symbols/Jackpot/Jackpot44.png",
    slots10_44:  "/src/sprites/Symbols/Jackpot/Jackpot45.png",
    slots10_45:  "/src/sprites/Symbols/Jackpot/Jackpot46.png",
    slots10_46:  "/src/sprites/Symbols/Jackpot/Jackpot47.png",
    slots10_47:  "/src/sprites/Symbols/Jackpot/Jackpot48.png",

    slots11_0 :  "/src/sprites/Symbols/Wild/Wild1.png",
    slots11_1 :  "/src/sprites/Symbols/Wild/Wild2.png",
    slots11_2 :  "/src/sprites/Symbols/Wild/Wild3.png",
    slots11_3 :  "/src/sprites/Symbols/Wild/Wild4.png",
    slots11_4 :  "/src/sprites/Symbols/Wild/Wild5.png",
    slots11_5 :  "/src/sprites/Symbols/Wild/Wild6.png",
    slots11_6 :  "/src/sprites/Symbols/Wild/Wild7.png",
    slots11_7 :  "/src/sprites/Symbols/Wild/Wild8.png",
    slots11_8 :  "/src/sprites/Symbols/Wild/Wild9.png",
    slots11_9 :  "/src/sprites/Symbols/Wild/Wild10.png",
    slots11_10:  "/src/sprites/Symbols/Wild/Wild11.png",
    slots11_11:  "/src/sprites/Symbols/Wild/Wild12.png",
    slots11_12:  "/src/sprites/Symbols/Wild/Wild13.png",
    slots11_13:  "/src/sprites/Symbols/Wild/Wild14.png",
    slots11_14:  "/src/sprites/Symbols/Wild/Wild15.png",
    slots11_15:  "/src/sprites/Symbols/Wild/Wild16.png",
    slots11_16:  "/src/sprites/Symbols/Wild/Wild17.png",
    slots11_17:  "/src/sprites/Symbols/Wild/Wild18.png",
    slots11_18:  "/src/sprites/Symbols/Wild/Wild19.png",
    slots11_19:  "/src/sprites/Symbols/Wild/Wild20.png",
    slots11_20:  "/src/sprites/Symbols/Wild/Wild21.png",
    slots11_21:  "/src/sprites/Symbols/Wild/Wild22.png",
    slots11_22:  "/src/sprites/Symbols/Wild/Wild23.png",
    slots11_23:  "/src/sprites/Symbols/Wild/Wild24.png",
    slots11_24:  "/src/sprites/Symbols/Wild/Wild25.png",
    slots11_25:  "/src/sprites/Symbols/Wild/Wild26.png",
    slots11_26:  "/src/sprites/Symbols/Wild/Wild27.png",
    slots11_27:  "/src/sprites/Symbols/Wild/Wild28.png",
    slots11_28:  "/src/sprites/Symbols/Wild/Wild29.png",
    slots11_29:  "/src/sprites/Symbols/Wild/Wild30.png",
    slots11_30:  "/src/sprites/Symbols/Wild/Wild31.png",
    slots11_31:  "/src/sprites/Symbols/Wild/Wild32.png",
    slots11_32:  "/src/sprites/Symbols/Wild/Wild33.png",
    slots11_33:  "/src/sprites/Symbols/Wild/Wild34.png",
    slots11_34:  "/src/sprites/Symbols/Wild/Wild35.png",
    slots11_35:  "/src/sprites/Symbols/Wild/Wild36.png",
    slots11_36:  "/src/sprites/Symbols/Wild/Wild37.png",
    slots11_37:  "/src/sprites/Symbols/Wild/Wild38.png",
    slots11_38:  "/src/sprites/Symbols/Wild/Wild39.png",
    slots11_39:  "/src/sprites/Symbols/Wild/Wild40.png",
    slots11_40:  "/src/sprites/Symbols/Wild/Wild41.png",
    slots11_41:  "/src/sprites/Symbols/Wild/Wild42.png",
    slots11_42:  "/src/sprites/Symbols/Wild/Wild43.png",
    slots11_43:  "/src/sprites/Symbols/Wild/Wild44.png",
    slots11_44:  "/src/sprites/Symbols/Wild/Wild45.png",
    slots11_45:  "/src/sprites/Symbols/Wild/Wild46.png",
    slots11_46:  "/src/sprites/Symbols/Wild/Wild47.png",
    slots11_47:  "/src/sprites/Symbols/Wild/Wild48.png",

    slots12_0 :  "/src/sprites/Symbols/Scatter/Scatter2.png",
    slots12_1 :  "/src/sprites/Symbols/Scatter/Scatter3.png",
    slots12_2 :  "/src/sprites/Symbols/Scatter/Scatter4.png",
    slots12_3 :  "/src/sprites/Symbols/Scatter/Scatter5.png",
    slots12_4 :  "/src/sprites/Symbols/Scatter/Scatter6.png",
    slots12_5 :  "/src/sprites/Symbols/Scatter/Scatter7.png",
    slots12_6 :  "/src/sprites/Symbols/Scatter/Scatter8.png",
    slots12_7 :  "/src/sprites/Symbols/Scatter/Scatter9.png",
    slots12_8 :  "/src/sprites/Symbols/Scatter/Scatter10.png",
    slots12_9 :  "/src/sprites/Symbols/Scatter/Scatter11.png",
    slots12_10:  "/src/sprites/Symbols/Scatter/Scatter12.png",
    slots12_11:  "/src/sprites/Symbols/Scatter/Scatter13.png",
    slots12_12:  "/src/sprites/Symbols/Scatter/Scatter14.png",
    slots12_13:  "/src/sprites/Symbols/Scatter/Scatter15.png",
    slots12_14:  "/src/sprites/Symbols/Scatter/Scatter16.png",
    slots12_15:  "/src/sprites/Symbols/Scatter/Scatter17.png",
    slots12_16:  "/src/sprites/Symbols/Scatter/Scatter18.png",
    slots12_17:  "/src/sprites/Symbols/Scatter/Scatter19.png",
    slots12_18:  "/src/sprites/Symbols/Scatter/Scatter20.png",
    slots12_19:  "/src/sprites/Symbols/Scatter/Scatter21.png",
    slots12_20:  "/src/sprites/Symbols/Scatter/Scatter22.png",
    slots12_21:  "/src/sprites/Symbols/Scatter/Scatter23.png",
    slots12_22:  "/src/sprites/Symbols/Scatter/Scatter24.png",
    slots12_23:  "/src/sprites/Symbols/Scatter/Scatter25.png",
    slots12_24:  "/src/sprites/Symbols/Scatter/Scatter26.png",
    slots12_25:  "/src/sprites/Symbols/Scatter/Scatter27.png",
    slots12_26:  "/src/sprites/Symbols/Scatter/Scatter28.png",
    slots12_27:  "/src/sprites/Symbols/Scatter/Scatter29.png",
    slots12_28:  "/src/sprites/Symbols/Scatter/Scatter30.png",
    slots12_29:  "/src/sprites/Symbols/Scatter/Scatter31.png",
    slots12_30:  "/src/sprites/Symbols/Scatter/Scatter32.png",
    slots12_31:  "/src/sprites/Symbols/Scatter/Scatter33.png",
    slots12_32:  "/src/sprites/Symbols/Scatter/Scatter34.png",
    slots12_33:  "/src/sprites/Symbols/Scatter/Scatter35.png",
    slots12_34:  "/src/sprites/Symbols/Scatter/Scatter36.png",
    slots12_35:  "/src/sprites/Symbols/Scatter/Scatter37.png",
    slots12_36:  "/src/sprites/Symbols/Scatter/Scatter38.png",
    slots12_37:  "/src/sprites/Symbols/Scatter/Scatter39.png",
    slots12_38:  "/src/sprites/Symbols/Scatter/Scatter40.png",
    slots12_39:  "/src/sprites/Symbols/Scatter/Scatter41.png",
    slots12_40:  "/src/sprites/Symbols/Scatter/Scatter42.png",
    slots12_41:  "/src/sprites/Symbols/Scatter/Scatter43.png",
    slots12_42:  "/src/sprites/Symbols/Scatter/Scatter44.png",
    slots12_43:  "/src/sprites/Symbols/Scatter/Scatter45.png",
    slots12_44:  "/src/sprites/Symbols/Scatter/Scatter46.png",
    slots12_45:  "/src/sprites/Symbols/Scatter/Scatter47.png",
    slots12_46:  "/src/sprites/Symbols/Scatter/Scatter48.png",

    slots13_0 :  "/src/sprites/Symbols/Bonus/Bonus1.png",
    slots13_1 :  "/src/sprites/Symbols/Bonus/Bonus2.png",
    slots13_2 :  "/src/sprites/Symbols/Bonus/Bonus3.png",
    slots13_3 :  "/src/sprites/Symbols/Bonus/Bonus4.png",
    slots13_4 :  "/src/sprites/Symbols/Bonus/Bonus5.png",
    slots13_5 :  "/src/sprites/Symbols/Bonus/Bonus6.png",
    slots13_6 :  "/src/sprites/Symbols/Bonus/Bonus7.png",
    slots13_7 :  "/src/sprites/Symbols/Bonus/Bonus8.png",
    slots13_8 :  "/src/sprites/Symbols/Bonus/Bonus9.png",
    slots13_9 :  "/src/sprites/Symbols/Bonus/Bonus10.png",
    slots13_10:  "/src/sprites/Symbols/Bonus/Bonus11.png",
    slots13_11:  "/src/sprites/Symbols/Bonus/Bonus12.png",
    slots13_12:  "/src/sprites/Symbols/Bonus/Bonus13.png",
    slots13_13:  "/src/sprites/Symbols/Bonus/Bonus14.png",
    slots13_14:  "/src/sprites/Symbols/Bonus/Bonus15.png",
    slots13_15:  "/src/sprites/Symbols/Bonus/Bonus16.png",
    slots13_16:  "/src/sprites/Symbols/Bonus/Bonus17.png",
    slots13_17:  "/src/sprites/Symbols/Bonus/Bonus18.png",
    slots13_18:  "/src/sprites/Symbols/Bonus/Bonus19.png",
    slots13_19:  "/src/sprites/Symbols/Bonus/Bonus20.png",
    slots13_20:  "/src/sprites/Symbols/Bonus/Bonus21.png",
    slots13_21:  "/src/sprites/Symbols/Bonus/Bonus22.png",
    slots13_22:  "/src/sprites/Symbols/Bonus/Bonus23.png",
    slots13_23:  "/src/sprites/Symbols/Bonus/Bonus24.png",
    slots13_24:  "/src/sprites/Symbols/Bonus/Bonus25.png",
    slots13_25:  "/src/sprites/Symbols/Bonus/Bonus26.png",
    slots13_26:  "/src/sprites/Symbols/Bonus/Bonus27.png",
    slots13_27:  "/src/sprites/Symbols/Bonus/Bonus28.png",
    slots13_28:  "/src/sprites/Symbols/Bonus/Bonus29.png",
    slots13_29:  "/src/sprites/Symbols/Bonus/Bonus30.png",
    slots13_30:  "/src/sprites/Symbols/Bonus/Bonus31.png",
    slots13_31:  "/src/sprites/Symbols/Bonus/Bonus32.png",
    slots13_32:  "/src/sprites/Symbols/Bonus/Bonus33.png",
    slots13_33:  "/src/sprites/Symbols/Bonus/Bonus34.png",
    slots13_34:  "/src/sprites/Symbols/Bonus/Bonus35.png",
    slots13_35:  "/src/sprites/Symbols/Bonus/Bonus36.png",
    slots13_36:  "/src/sprites/Symbols/Bonus/Bonus37.png",
    slots13_37:  "/src/sprites/Symbols/Bonus/Bonus38.png",
    slots13_38:  "/src/sprites/Symbols/Bonus/Bonus39.png",
    slots13_39:  "/src/sprites/Symbols/Bonus/Bonus40.png",
    slots13_40:  "/src/sprites/Symbols/Bonus/Bonus41.png",
    slots13_41:  "/src/sprites/Symbols/Bonus/Bonus42.png",
    slots13_42:  "/src/sprites/Symbols/Bonus/Bonus43.png",
    slots13_43:  "/src/sprites/Symbols/Bonus/Bonus44.png",
    slots13_44:  "/src/sprites/Symbols/Bonus/Bonus45.png",
    slots13_45:  "/src/sprites/Symbols/Bonus/Bonus46.png",
    slots13_47:  "/src/sprites/Symbols/Bonus/Bonus47.png",
    slots13_48:  "/src/sprites/Symbols/Bonus/Bonus48.png",

    slots14_0: "/src/sprites/Symbols/spin/FreeSpin1.png",
    slots14_1:  "/src/sprites/Symbols/spin/FreeSpin2.png",
    slots14_2:  "/src/sprites/Symbols/spin/FreeSpin3.png",
    slots14_3:  "/src/sprites/Symbols/spin/FreeSpin4.png",
    slots14_4:  "/src/sprites/Symbols/spin/FreeSpin5.png",
    slots14_5:  "/src/sprites/Symbols/spin/FreeSpin6.png",
    slots14_6:  "/src/sprites/Symbols/spin/FreeSpin7.png",
    slots14_7:  "/src/sprites/Symbols/spin/FreeSpin8.png",
    slots14_8:  "/src/sprites/Symbols/spin/FreeSpin9.png",
    slots14_9:  "/src/sprites/Symbols/spin/FreeSpin10.png",
    slots14_10:  "/src/sprites/Symbols/spin/FreeSpin11.png",
    slots14_11:  "/src/sprites/Symbols/spin/FreeSpin12.png",
    slots14_12:  "/src/sprites/Symbols/spin/FreeSpin13.png",
    slots14_13:  "/src/sprites/Symbols/spin/FreeSpin14.png",
    slots14_14:  "/src/sprites/Symbols/spin/FreeSpin15.png",
    slots14_15:  "/src/sprites/Symbols/spin/FreeSpin16.png",
    slots14_16:  "/src/sprites/Symbols/spin/FreeSpin17.png",
    slots14_17:  "/src/sprites/Symbols/spin/FreeSpin18.png",
    slots14_18:  "/src/sprites/Symbols/spin/FreeSpin19.png",
    slots14_19:  "/src/sprites/Symbols/spin/FreeSpin20.png",
    slots14_20:  "/src/sprites/Symbols/spin/FreeSpin21.png",
    slots14_21:  "/src/sprites/Symbols/spin/FreeSpin22.png",
    slots14_22:  "/src/sprites/Symbols/spin/FreeSpin23.png",
    slots14_23:  "/src/sprites/Symbols/spin/FreeSpin24.png",
    slots14_24:  "/src/sprites/Symbols/spin/FreeSpin25.png",
    slots14_25:  "/src/sprites/Symbols/spin/FreeSpin26.png",
    slots14_26:  "/src/sprites/Symbols/spin/FreeSpin27.png",
    slots14_27:  "/src/sprites/Symbols/spin/FreeSpin28.png",
    slots14_28:  "/src/sprites/Symbols/spin/FreeSpin29.png",
    slots14_29:  "/src/sprites/Symbols/spin/FreeSpin30.png",
    slots14_30:  "/src/sprites/Symbols/spin/FreeSpin31.png",
    slots14_31:  "/src/sprites/Symbols/spin/FreeSpin32.png",
    slots14_32:  "/src/sprites/Symbols/spin/FreeSpin33.png",
    slots14_33:  "/src/sprites/Symbols/spin/FreeSpin34.png",
    slots14_34:  "/src/sprites/Symbols/spin/FreeSpin35.png",
    slots14_35:  "/src/sprites/Symbols/spin/FreeSpin36.png",
    slots14_36:  "/src/sprites/Symbols/spin/FreeSpin37.png",
    slots14_37:  "/src/sprites/Symbols/spin/FreeSpin38.png",
    slots14_38:  "/src/sprites/Symbols/spin/FreeSpin39.png",
    slots14_39:  "/src/sprites/Symbols/spin/FreeSpin40.png",
    slots14_40:  "/src/sprites/Symbols/spin/FreeSpin41.png",
    slots14_41:  "/src/sprites/Symbols/spin/FreeSpin42.png",
    slots14_42:  "/src/sprites/Symbols/spin/FreeSpin43.png",
    slots14_43:  "/src/sprites/Symbols/spin/FreeSpin44.png",
    slots14_44:  "/src/sprites/Symbols/spin/FreeSpin45.png",
    slots14_45:  "/src/sprites/Symbols/spin/FreeSpin46.png",
    slots14_46:  "/src/sprites/Symbols/spin/FreeSpin47.png",
    slots14_47:  "/src/sprites/Symbols/spin/FreeSpin48.png",

    // firesheet: "src/sprites/FireSheet.png",
    // fire_1 :  "/src/sprites/Fire/Fire (1).png",
    // fire_2 :  "/src/sprites/Fire/Fire (2).png",
    // fire_3 :  "/src/sprites/Fire/Fire (3).png",
    // fire_4 :  "/src/sprites/Fire/Fire (4).png",
    // fire_5 :  "/src/sprites/Fire/Fire (5).png",
    // fire_6 :  "/src/sprites/Fire/Fire (6).png",
    // fire_7 :  "/src/sprites/Fire/Fire (7).png",
    // fire_8 :  "/src/sprites/Fire/Fire (8).png",
    // fire_9 :  "/src/sprites/Fire/Fire (9).png",
    // fire_10:  "/src/sprites/Fire/Fire (10).png",
    // fire_11:  "/src/sprites/Fire/Fire (11).png",
    // fire_12:  "/src/sprites/Fire/Fire (12).png",
    // fire_13:  "/src/sprites/Fire/Fire (13).png",
    // fire_14:  "/src/sprites/Fire/Fire (14).png",
    // fire_15:  "/src/sprites/Fire/Fire (15).png",
    // fire_16:  "/src/sprites/Fire/Fire (16).png",
    // fire_17:  "/src/sprites/Fire/Fire (17).png",
    // fire_18:  "/src/sprites/Fire/Fire (18).png",
    // fire_19:  "/src/sprites/Fire/Fire (19).png",
    // fire_20:  "/src/sprites/Fire/Fire (20).png",
    // fire_21:  "/src/sprites/Fire/Fire (21).png",
    // fire_22:  "/src/sprites/Fire/Fire (22).png",
    // fire_23:  "/src/sprites/Fire/Fire (23).png",
    
}



export const staticData = {
    // logoURL: "https://cccdn.b-cdn.net/1584464368856.png",
    // logoURL:  "/static/logo.png").default,
    Background:  "src/sprites/Background.jpg",
};

export const fontData = ["Montserrat"];



export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.wav",
        spinWheelMusic: "src/sounds/spinWheel.mp3"
 
};

export const preloaderConfig = {
    // startLogo:  "/src/sprites/Logo.png")
}